// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyTemplate(arg1) {
  return window['go']['backend']['App']['ApplyTemplate'](arg1);
}

export function BuildCopyPreviousWeekPlan(arg1) {
  return window['go']['backend']['App']['BuildCopyPreviousWeekPlan'](arg1);
}

export function BuildGitSuggestion(arg1) {
  return window['go']['backend']['App']['BuildGitSuggestion'](arg1);
}

export function CheckForUpdate() {
  return window['go']['backend']['App']['CheckForUpdate']();
}

export function CheckForUpdateNow() {
  return window['go']['backend']['App']['CheckForUpdateNow']();
}

export function CheckPlanConflicts(arg1) {
  return window['go']['backend']['App']['CheckPlanConflicts'](arg1);
}

export function ClearHolidayCache() {
  return window['go']['backend']['App']['ClearHolidayCache']();
}

export function ClearSavedTasks() {
  return window['go']['backend']['App']['ClearSavedTasks']();
}

export function ConnectWithToken(arg1, arg2) {
  return window['go']['backend']['App']['ConnectWithToken'](arg1, arg2);
}

export function CorruptedConfigBackups() {
  return window['go']['backend']['App']['CorruptedConfigBackups']();
}

export function CreateDistributionPlan(arg1, arg2) {
  return window['go']['backend']['App']['CreateDistributionPlan'](arg1, arg2);
}

export function DeleteMultipleTimeEntries(arg1) {
  return window['go']['backend']['App']['DeleteMultipleTimeEntries'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['backend']['App']['DeleteTemplate'](arg1);
}

export function DiscardTimer() {
  return window['go']['backend']['App']['DiscardTimer']();
}

export function DownloadAndInstallUpdate() {
  return window['go']['backend']['App']['DownloadAndInstallUpdate']();
}

export function DownloadCurrentMonthReport() {
  return window['go']['backend']['App']['DownloadCurrentMonthReport']();
}

export function DownloadTimeReport(arg1, arg2) {
  return window['go']['backend']['App']['DownloadTimeReport'](arg1, arg2);
}

export function ExportTimeReportCSV(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ExportTimeReportCSV'](arg1, arg2, arg3);
}

export function GetAllNonWorkingDays(arg1, arg2) {
  return window['go']['backend']['App']['GetAllNonWorkingDays'](arg1, arg2);
}

export function GetAppSettings() {
  return window['go']['backend']['App']['GetAppSettings']();
}

export function GetAppVersion() {
  return window['go']['backend']['App']['GetAppVersion']();
}

export function GetBrazilianHolidays(arg1) {
  return window['go']['backend']['App']['GetBrazilianHolidays'](arg1);
}

export function GetBrazilianStates() {
  return window['go']['backend']['App']['GetBrazilianStates']();
}

export function GetDashboardStats() {
  return window['go']['backend']['App']['GetDashboardStats']();
}

export function GetExtraNonWorkingDays(arg1) {
  return window['go']['backend']['App']['GetExtraNonWorkingDays'](arg1);
}

export function GetGitIntegration() {
  return window['go']['backend']['App']['GetGitIntegration']();
}

export function GetGitSuggestion(arg1) {
  return window['go']['backend']['App']['GetGitSuggestion'](arg1);
}

export function GetHolidayCacheStats() {
  return window['go']['backend']['App']['GetHolidayCacheStats']();
}

export function GetLegacyInstall() {
  return window['go']['backend']['App']['GetLegacyInstall']();
}

export function GetLoggedTimeFromCalendarAPI(arg1, arg2) {
  return window['go']['backend']['App']['GetLoggedTimeFromCalendarAPI'](arg1, arg2);
}

export function GetLogsPath() {
  return window['go']['backend']['App']['GetLogsPath']();
}

export function GetNotificationStatus() {
  return window['go']['backend']['App']['GetNotificationStatus']();
}

export function GetProjects() {
  return window['go']['backend']['App']['GetProjects']();
}

export function GetPublicConfig() {
  return window['go']['backend']['App']['GetPublicConfig']();
}

export function GetRecentActivities() {
  return window['go']['backend']['App']['GetRecentActivities']();
}

export function GetReminderSettings() {
  return window['go']['backend']['App']['GetReminderSettings']();
}

export function GetSavedTasks() {
  return window['go']['backend']['App']['GetSavedTasks']();
}

export function GetTasks() {
  return window['go']['backend']['App']['GetTasks']();
}

export function GetTasksByProject(arg1) {
  return window['go']['backend']['App']['GetTasksByProject'](arg1);
}

export function GetTasksWithUpcomingDeadlines() {
  return window['go']['backend']['App']['GetTasksWithUpcomingDeadlines']();
}

export function GetTemplates() {
  return window['go']['backend']['App']['GetTemplates']();
}

export function GetTimeEntriesForPeriod(arg1, arg2) {
  return window['go']['backend']['App']['GetTimeEntriesForPeriod'](arg1, arg2);
}

export function GetTimeEntriesForPeriodV2(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetTimeEntriesForPeriodV2'](arg1, arg2, arg3);
}

export function GetTimeReportSummary(arg1, arg2) {
  return window['go']['backend']['App']['GetTimeReportSummary'](arg1, arg2);
}

export function GetTimeTotalsForPeriod(arg1, arg2) {
  return window['go']['backend']['App']['GetTimeTotalsForPeriod'](arg1, arg2);
}

export function GetTimerSettings() {
  return window['go']['backend']['App']['GetTimerSettings']();
}

export function GetTimerState() {
  return window['go']['backend']['App']['GetTimerState']();
}

export function GetUserProfile() {
  return window['go']['backend']['App']['GetUserProfile']();
}

export function GetWeekGrid(arg1) {
  return window['go']['backend']['App']['GetWeekGrid'](arg1);
}

export function GetWorkCalendarSettings() {
  return window['go']['backend']['App']['GetWorkCalendarSettings']();
}

export function GetWorkingDays(arg1, arg2) {
  return window['go']['backend']['App']['GetWorkingDays'](arg1, arg2);
}

export function IsConfigured() {
  return window['go']['backend']['App']['IsConfigured']();
}

export function IsWorkDay(arg1) {
  return window['go']['backend']['App']['IsWorkDay'](arg1);
}

export function LegacyCredentialPurged() {
  return window['go']['backend']['App']['LegacyCredentialPurged']();
}

export function LogMultipleTimes(arg1) {
  return window['go']['backend']['App']['LogMultipleTimes'](arg1);
}

export function Logout() {
  return window['go']['backend']['App']['Logout']();
}

export function OpenDirectoryPath(arg1) {
  return window['go']['backend']['App']['OpenDirectoryPath'](arg1);
}

export function OpenLogsFolder() {
  return window['go']['backend']['App']['OpenLogsFolder']();
}

export function OpenReleasePage() {
  return window['go']['backend']['App']['OpenReleasePage']();
}

export function PauseTimer() {
  return window['go']['backend']['App']['PauseTimer']();
}

export function PlanFillGaps(arg1) {
  return window['go']['backend']['App']['PlanFillGaps'](arg1);
}

export function PreloadHolidays() {
  return window['go']['backend']['App']['PreloadHolidays']();
}

export function PreviewTimerStop() {
  return window['go']['backend']['App']['PreviewTimerStop']();
}

export function RefreshHolidaysForYear(arg1) {
  return window['go']['backend']['App']['RefreshHolidaysForYear'](arg1);
}

export function RemoveTask(arg1) {
  return window['go']['backend']['App']['RemoveTask'](arg1);
}

export function ResumeTimer() {
  return window['go']['backend']['App']['ResumeTimer']();
}

export function RunLegacyUninstaller() {
  return window['go']['backend']['App']['RunLegacyUninstaller']();
}

export function SaveAppSettings(arg1) {
  return window['go']['backend']['App']['SaveAppSettings'](arg1);
}

export function SaveGitIntegration(arg1) {
  return window['go']['backend']['App']['SaveGitIntegration'](arg1);
}

export function SaveReminderSettings(arg1) {
  return window['go']['backend']['App']['SaveReminderSettings'](arg1);
}

export function SaveTask(arg1) {
  return window['go']['backend']['App']['SaveTask'](arg1);
}

export function SaveTemplate(arg1) {
  return window['go']['backend']['App']['SaveTemplate'](arg1);
}

export function SaveTimerSettings(arg1) {
  return window['go']['backend']['App']['SaveTimerSettings'](arg1);
}

export function SaveWorkCalendarSettings(arg1) {
  return window['go']['backend']['App']['SaveWorkCalendarSettings'](arg1);
}

export function SelectGitRepository() {
  return window['go']['backend']['App']['SelectGitRepository']();
}

export function SendTestReminder() {
  return window['go']['backend']['App']['SendTestReminder']();
}

export function SetMinutosPorDia(arg1) {
  return window['go']['backend']['App']['SetMinutosPorDia'](arg1);
}

export function StartTimer(arg1, arg2, arg3) {
  return window['go']['backend']['App']['StartTimer'](arg1, arg2, arg3);
}

export function StopTimer(arg1, arg2, arg3) {
  return window['go']['backend']['App']['StopTimer'](arg1, arg2, arg3);
}

export function UpdateTimeEntry(arg1, arg2) {
  return window['go']['backend']['App']['UpdateTimeEntry'](arg1, arg2);
}
