// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {planning} from '../models';
import {gitlog} from '../models';
import {update} from '../models';
import {api} from '../models';
import {timer} from '../models';
import {config} from '../models';
import {holidays} from '../models';
import {legacy} from '../models';
import {backend} from '../models';
import {reports} from '../models';
import {audit} from '../models';

export function ApplyTemplate(arg1:string):Promise<void>;

export function BuildCopyPreviousWeekPlan(arg1:string):Promise<planning.CopyPlan>;

export function BuildGitSuggestion(arg1:Array<gitlog.Commit>):Promise<string>;

export function CheckForUpdate():Promise<update.Info>;

export function CheckForUpdateNow():Promise<update.Info>;

export function CheckPlanConflicts(arg1:Array<api.WorkDay>):Promise<Array<api.DayConflict>>;

export function ClearHolidayCache():Promise<void>;

export function ClearSavedTasks():Promise<void>;

export function ConnectWithToken(arg1:string,arg2:string):Promise<api.LoginResponse>;

export function CorruptedConfigBackups():Promise<Array<string>>;

export function CreateDistributionPlan(arg1:Array<string>,arg2:Array<api.Task>):Promise<Array<api.WorkDay>>;

export function DeleteMultipleTimeEntries(arg1:Array<number>):Promise<Array<api.DeleteTimeEntryResult>>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function DiscardTimer():Promise<timer.State>;

export function DownloadAndInstallUpdate():Promise<void>;

export function DownloadCurrentMonthReport():Promise<string>;

export function DownloadTimeReport(arg1:string,arg2:string):Promise<string>;

export function ExportTimeReportCSV(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function GetAllNonWorkingDays(arg1:number,arg2:number):Promise<Array<Record<string, any>>>;

export function GetAppSettings():Promise<config.AppSettings>;

export function GetAppVersion():Promise<string>;

export function GetAuditSettings():Promise<config.AuditSettings>;

export function GetBrazilianHolidays(arg1:number):Promise<Array<api.Holiday>>;

export function GetBrazilianStates():Promise<Array<holidays.State>>;

export function GetDashboardStats():Promise<Record<string, any>>;

export function GetExtraNonWorkingDays(arg1:number):Promise<Array<holidays.DayInfo>>;

export function GetGitIntegration():Promise<config.GitIntegration>;

export function GetGitSuggestion(arg1:string):Promise<gitlog.Result>;

export function GetHolidayCacheStats():Promise<api.HolidayCacheStats>;

export function GetLegacyInstall():Promise<legacy.Install>;

export function GetLoggedTimeFromCalendarAPI(arg1:number,arg2:number):Promise<api.LoggedTimeResponse>;

export function GetLogsPath():Promise<string>;

export function GetNotificationStatus():Promise<backend.NotificationStatus>;

export function GetProjects():Promise<Array<api.Project>>;

export function GetPublicConfig():Promise<api.PublicConfig>;

export function GetRecentActivities():Promise<Array<Record<string, any>>>;

export function GetReminderSettings():Promise<config.ReminderSettings>;

export function GetSavedTasks():Promise<Array<api.Task>>;

export function GetTasks():Promise<Array<api.TeamworkTask>>;

export function GetTasksByProject(arg1:number):Promise<Array<api.TeamworkTask>>;

export function GetTasksWithUpcomingDeadlines():Promise<Array<Record<string, any>>>;

export function GetTemplates():Promise<Record<string, api.Template>>;

export function GetTimeEntriesForPeriod(arg1:string,arg2:string):Promise<Array<api.TimeEntryReport>>;

export function GetTimeEntriesForPeriodV2(arg1:string,arg2:string,arg3:boolean):Promise<Array<api.TimeEntryReport>>;

export function GetTimeReportSummary(arg1:string,arg2:string):Promise<reports.Report>;

export function GetTimeTotalsForPeriod(arg1:string,arg2:string):Promise<api.TimeTotal>;

export function GetTimerSettings():Promise<config.TimerSettings>;

export function GetTimerState():Promise<timer.State>;

export function GetUserProfile():Promise<backend.UserProfile>;

export function GetWeekGrid(arg1:string):Promise<planning.WeekGrid>;

export function GetWorkCalendarSettings():Promise<config.CalendarSettings>;

export function GetWorkingDays(arg1:string,arg2:string):Promise<Array<string>>;

export function IgnoreAuditIssue(arg1:string):Promise<void>;

export function IsConfigured():Promise<boolean>;

export function IsWorkDay(arg1:string):Promise<boolean>;

export function LegacyCredentialPurged():Promise<boolean>;

export function LogMultipleTimes(arg1:Array<api.WorkDay>):Promise<Array<api.TimeLogResult>>;

export function Logout():Promise<void>;

export function OpenDirectoryPath(arg1:string):Promise<void>;

export function OpenLogsFolder():Promise<void>;

export function OpenReleasePage():Promise<void>;

export function PauseTimer():Promise<timer.State>;

export function PlanFillGaps(arg1:backend.FillGapsRequest):Promise<backend.FillGapsResult>;

export function PreloadHolidays():Promise<void>;

export function PreviewTimerStop():Promise<Array<timer.Entry>>;

export function RefreshHolidaysForYear(arg1:number):Promise<Array<api.Holiday>>;

export function RemoveTask(arg1:number):Promise<void>;

export function ResumeTimer():Promise<timer.State>;

export function RunLegacyUninstaller():Promise<void>;

export function RunMonthAudit(arg1:number,arg2:number):Promise<audit.Result>;

export function SaveAppSettings(arg1:config.AppSettings):Promise<void>;

export function SaveAuditSettings(arg1:config.AuditSettings):Promise<void>;

export function SaveGitIntegration(arg1:config.GitIntegration):Promise<void>;

export function SaveReminderSettings(arg1:config.ReminderSettings):Promise<void>;

export function SaveTask(arg1:api.Task):Promise<void>;

export function SaveTemplate(arg1:api.Template):Promise<void>;

export function SaveTimerSettings(arg1:config.TimerSettings):Promise<void>;

export function SaveWorkCalendarSettings(arg1:config.CalendarSettings):Promise<config.CalendarSettings>;

export function SelectGitRepository():Promise<string>;

export function SendTestReminder():Promise<void>;

export function SetMinutosPorDia(arg1:number):Promise<void>;

export function StartTimer(arg1:timer.TaskRef,arg2:string,arg3:boolean):Promise<timer.State>;

export function StopTimer(arg1:boolean,arg2:string,arg3:Array<timer.Entry>):Promise<timer.StopResult>;

export function UnignoreAuditIssue(arg1:string):Promise<void>;

export function UpdateTimeEntry(arg1:number,arg2:api.TimeEntry):Promise<api.TimeLogResult>;
