// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyTemplate(arg1) {
  return window['go']['backend']['App']['ApplyTemplate'](arg1);
}

export function CalculateTotalMinutes(arg1) {
  return window['go']['backend']['App']['CalculateTotalMinutes'](arg1);
}

export function ClearSavedTasks() {
  return window['go']['backend']['App']['ClearSavedTasks']();
}

export function CreateDistributionPlan(arg1, arg2) {
  return window['go']['backend']['App']['CreateDistributionPlan'](arg1, arg2);
}

export function CreateDistributionPlanFromLoggedTime(arg1, arg2, arg3) {
  return window['go']['backend']['App']['CreateDistributionPlanFromLoggedTime'](arg1, arg2, arg3);
}

export function DeleteMultipleTimeEntries(arg1) {
  return window['go']['backend']['App']['DeleteMultipleTimeEntries'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['backend']['App']['DeleteTemplate'](arg1);
}

export function DeleteTimeEntry(arg1) {
  return window['go']['backend']['App']['DeleteTimeEntry'](arg1);
}

export function DeleteTimeEntryV2(arg1) {
  return window['go']['backend']['App']['DeleteTimeEntryV2'](arg1);
}

export function DownloadCurrentMonthReport() {
  return window['go']['backend']['App']['DownloadCurrentMonthReport']();
}

export function DownloadTimeReport(arg1, arg2) {
  return window['go']['backend']['App']['DownloadTimeReport'](arg1, arg2);
}

export function GetAllNonWorkingDays(arg1, arg2) {
  return window['go']['backend']['App']['GetAllNonWorkingDays'](arg1, arg2);
}

export function GetAllTimeEntriesForDay(arg1) {
  return window['go']['backend']['App']['GetAllTimeEntriesForDay'](arg1);
}

export function GetAppSettings() {
  return window['go']['backend']['App']['GetAppSettings']();
}

export function GetBrazilianHolidays(arg1) {
  return window['go']['backend']['App']['GetBrazilianHolidays'](arg1);
}

export function GetConfig() {
  return window['go']['backend']['App']['GetConfig']();
}

export function GetCurrentUserId() {
  return window['go']['backend']['App']['GetCurrentUserId']();
}

export function GetCurrentUserIdWithConfig(arg1) {
  return window['go']['backend']['App']['GetCurrentUserIdWithConfig'](arg1);
}

export function GetDashboardStats() {
  return window['go']['backend']['App']['GetDashboardStats']();
}

export function GetDeletedTimeEntries(arg1, arg2) {
  return window['go']['backend']['App']['GetDeletedTimeEntries'](arg1, arg2);
}

export function GetEntriesFromLoggedTime(arg1, arg2) {
  return window['go']['backend']['App']['GetEntriesFromLoggedTime'](arg1, arg2);
}

export function GetHolidaysForMonth(arg1, arg2) {
  return window['go']['backend']['App']['GetHolidaysForMonth'](arg1, arg2);
}

export function GetLoggedTimeFromCalendarAPI(arg1, arg2) {
  return window['go']['backend']['App']['GetLoggedTimeFromCalendarAPI'](arg1, arg2);
}

export function GetProjects() {
  return window['go']['backend']['App']['GetProjects']();
}

export function GetRecentActivities() {
  return window['go']['backend']['App']['GetRecentActivities']();
}

export function GetSavedTasks() {
  return window['go']['backend']['App']['GetSavedTasks']();
}

export function GetTaskDetails(arg1) {
  return window['go']['backend']['App']['GetTaskDetails'](arg1);
}

export function GetTasks() {
  return window['go']['backend']['App']['GetTasks']();
}

export function GetTasksByProject(arg1) {
  return window['go']['backend']['App']['GetTasksByProject'](arg1);
}

export function GetTasksWithUpcomingDeadlines() {
  return window['go']['backend']['App']['GetTasksWithUpcomingDeadlines']();
}

export function GetTemplate(arg1) {
  return window['go']['backend']['App']['GetTemplate'](arg1);
}

export function GetTemplates() {
  return window['go']['backend']['App']['GetTemplates']();
}

export function GetTimeEntriesForPeriod(arg1, arg2) {
  return window['go']['backend']['App']['GetTimeEntriesForPeriod'](arg1, arg2);
}

export function GetTimeEntriesForPeriodV2(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetTimeEntriesForPeriodV2'](arg1, arg2, arg3);
}

export function GetTimeEntriesWithDetails(arg1, arg2) {
  return window['go']['backend']['App']['GetTimeEntriesWithDetails'](arg1, arg2);
}

export function GetTimeTotalsForPeriod(arg1, arg2) {
  return window['go']['backend']['App']['GetTimeTotalsForPeriod'](arg1, arg2);
}

export function GetUserProfile() {
  return window['go']['backend']['App']['GetUserProfile']();
}

export function GetWorkingDays(arg1, arg2) {
  return window['go']['backend']['App']['GetWorkingDays'](arg1, arg2);
}

export function IsWorkDay(arg1) {
  return window['go']['backend']['App']['IsWorkDay'](arg1);
}

export function LogMultipleTimes(arg1) {
  return window['go']['backend']['App']['LogMultipleTimes'](arg1);
}

export function LogTime(arg1, arg2) {
  return window['go']['backend']['App']['LogTime'](arg1, arg2);
}

export function LoginWithCredentials(arg1, arg2, arg3) {
  return window['go']['backend']['App']['LoginWithCredentials'](arg1, arg2, arg3);
}

export function OpenDirectoryPath(arg1) {
  return window['go']['backend']['App']['OpenDirectoryPath'](arg1);
}

export function RemoveTask(arg1) {
  return window['go']['backend']['App']['RemoveTask'](arg1);
}

export function SaveAppSettings(arg1) {
  return window['go']['backend']['App']['SaveAppSettings'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['backend']['App']['SaveConfig'](arg1);
}

export function SaveTask(arg1) {
  return window['go']['backend']['App']['SaveTask'](arg1);
}

export function SaveTemplate(arg1) {
  return window['go']['backend']['App']['SaveTemplate'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['backend']['App']['TestConnection'](arg1);
}
