// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalcularTotalMinutos(arg1) {
  return window['go']['backend']['App']['CalcularTotalMinutos'](arg1);
}

export function CriarPlanoDistribuicao(arg1, arg2) {
  return window['go']['backend']['App']['CriarPlanoDistribuicao'](arg1, arg2);
}

export function DeleteTemplate(arg1) {
  return window['go']['backend']['App']['DeleteTemplate'](arg1);
}

export function GetAppSettings() {
  return window['go']['backend']['App']['GetAppSettings']();
}

export function GetConfig() {
  return window['go']['backend']['App']['GetConfig']();
}

export function GetCurrentUserId() {
  return window['go']['backend']['App']['GetCurrentUserId']();
}

export function GetCurrentUserIdWithConfig(arg1) {
  return window['go']['backend']['App']['GetCurrentUserIdWithConfig'](arg1);
}

export function GetProjects() {
  return window['go']['backend']['App']['GetProjects']();
}

export function GetSavedTasks() {
  return window['go']['backend']['App']['GetSavedTasks']();
}

export function GetTaskDetails(arg1) {
  return window['go']['backend']['App']['GetTaskDetails'](arg1);
}

export function GetTasks() {
  return window['go']['backend']['App']['GetTasks']();
}

export function GetTasksByProject(arg1) {
  return window['go']['backend']['App']['GetTasksByProject'](arg1);
}

export function GetTemplate(arg1) {
  return window['go']['backend']['App']['GetTemplate'](arg1);
}

export function GetTemplates() {
  return window['go']['backend']['App']['GetTemplates']();
}

export function LogMultipleTimes(arg1) {
  return window['go']['backend']['App']['LogMultipleTimes'](arg1);
}

export function LogTime(arg1, arg2) {
  return window['go']['backend']['App']['LogTime'](arg1, arg2);
}

export function ObterDiasUteis(arg1, arg2) {
  return window['go']['backend']['App']['ObterDiasUteis'](arg1, arg2);
}

export function RemoveTask(arg1) {
  return window['go']['backend']['App']['RemoveTask'](arg1);
}

export function SaveAppSettings(arg1) {
  return window['go']['backend']['App']['SaveAppSettings'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['backend']['App']['SaveConfig'](arg1);
}

export function SaveTask(arg1) {
  return window['go']['backend']['App']['SaveTask'](arg1);
}

export function SaveTemplate(arg1) {
  return window['go']['backend']['App']['SaveTemplate'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['backend']['App']['TestConnection'](arg1);
}
