// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {config} from '../models';

export function CalcularTotalMinutos(arg1:Array<api.Task>):Promise<number>;

export function CriarPlanoDistribuicao(arg1:Array<string>,arg2:Array<api.Task>):Promise<Array<api.WorkDay>>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function GetAppSettings():Promise<config.AppSettings>;

export function GetConfig():Promise<api.Config>;

export function GetCurrentUserId():Promise<number>;

export function GetCurrentUserIdWithConfig(arg1:api.Config):Promise<number>;

export function GetProjects():Promise<Array<api.Project>>;

export function GetSavedTasks():Promise<Array<api.Task>>;

export function GetTaskDetails(arg1:number):Promise<api.TeamworkTask>;

export function GetTasks():Promise<Array<api.TeamworkTask>>;

export function GetTasksByProject(arg1:number):Promise<Array<api.TeamworkTask>>;

export function GetTemplate(arg1:string):Promise<api.Template|boolean>;

export function GetTemplates():Promise<Record<string, api.Template>>;

export function LogMultipleTimes(arg1:Array<api.WorkDay>):Promise<Array<api.TimeLogResult>>;

export function LogTime(arg1:number,arg2:api.TimeEntry):Promise<api.TimeLogResult>;

export function LoginWithCredentials(arg1:string,arg2:string,arg3:string):Promise<api.LoginResponse>;

export function ObterDiasUteis(arg1:string,arg2:string):Promise<Array<string>>;

export function RemoveTask(arg1:number):Promise<void>;

export function SaveAppSettings(arg1:config.AppSettings):Promise<void>;

export function SaveConfig(arg1:api.Config):Promise<void>;

export function SaveTask(arg1:api.Task):Promise<void>;

export function SaveTemplate(arg1:api.Template):Promise<void>;

export function TestConnection(arg1:api.Config):Promise<Array<any>>;
